### ISSUE TITLE
Seek bar and delay features

### ISSUE THREAD

**Issue by arthur-digby** [svt/vivictpp#10]
Are there any plans to add a seekbar control? It would help a lot. Using the 5 second advance works but it is slow and it is impractical to use on videos longer than 1 or 2 minutes.

Also, a delay between the 2 videos is sometimes necessary to be able to compare them. Is this on the roadmap?

Thank you for developing this app. It has a great potential.

**Comment by grusell** [comment]
Yes, I actually did add a seekbar at one point recently, but unfortunately had to remove it again as part of a rewrite. I will try to implement this again as soon as possible.

Yes, the possibility to add a delay between the 2 videos is also on my list of things to add. Since you are asking for it, I guess I will move it up the list :) .

**Comment by grusell** [comment]
Delay feature implemented in v0.1.11, use keys '<' and '>' (us keyboard) to decrease/increase delay by one frame.

Seek bar still not present, but now shift-m, alt-shift-m, shift-/, alt-shift-/ can be use to seek forward/backward 1 minute or 10 minutes.

**Comment by arthur-digby** [comment]
Thanks!
